//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Services {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.IOrderService")]
    public interface IOrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        void AddOrder(int customerId, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AddOrder", ReplyAction="http://tempuri.org/IOrderService/AddOrderResponse")]
        System.Threading.Tasks.Task AddOrderAsync(int customerId, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AsyncAddOrder", ReplyAction="http://tempuri.org/IOrderService/AsyncAddOrderResponse")]
        void AsyncAddOrder(int customerId, decimal price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderService/AsyncAddOrder", ReplyAction="http://tempuri.org/IOrderService/AsyncAddOrderResponse")]
        System.Threading.Tasks.Task AsyncAddOrderAsync(int customerId, decimal price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderServiceChannel : API.Services.IOrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<API.Services.IOrderService>, API.Services.IOrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddOrder(int customerId, decimal price) {
            base.Channel.AddOrder(customerId, price);
        }
        
        public System.Threading.Tasks.Task AddOrderAsync(int customerId, decimal price) {
            return base.Channel.AddOrderAsync(customerId, price);
        }
        
        public void AsyncAddOrder(int customerId, decimal price) {
            base.Channel.AsyncAddOrder(customerId, price);
        }
        
        public System.Threading.Tasks.Task AsyncAddOrderAsync(int customerId, decimal price) {
            return base.Channel.AsyncAddOrderAsync(customerId, price);
        }
    }
}
