//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public decimal Price { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int Customer_Id { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
