// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Domain.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialStructure : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialStructure));
        
        string IMigrationMetadata.Id
        {
            get { return "201602092130425_InitialStructure"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
